Capability exchanges
DSD-DBS/py-capellambse pull request #102
Opened 2022-06-21 12:41 UTC by ewuerger

This PR increases coverage of endpoints of the SystemArchitectureLayer. Specifically the Mission receives new attributes: exploits, involvements and exploitations. `.exploits` works as ashortcut to get to the exploited OperationalCapabilities rightaway. Capability and OperationalCapability Exchanges: include, extend and generalizations are added. Special focus on `.incoming_exploitations` which is a mandatory attribute on Capabilites enabling fast tracking of which Missions are in the context of a Capability.

Then for rendering of [MCB] and [OCB] diagrams it was needed to add default styling. Additionally we finally did a refactoring of svg.drawing.py where `LabelBuilder` and `LinesData` were added to remove the amount of parameters. These were similar on various methods. On top we refactored the derimental _draw_label method such that it is more readable and critical steps are outsourced in their own function. This is very needed b/c _draw_label is the core label producing method called in box, edge and symbol labeling.

Finally the text in OperationalCapabilitySymbol (OC) was way too bold and didn't reuse _brown_oval that is used by mission and capability symbol factories. This was also changed.

2022-06-22 10:57 UTC, Wuestengecko requested changes
I'm gonna make the bold assumption that you have tested all the new calculations that you introduced, so I only have a few minor points about code style to make. ;)

2022-06-23 07:15 UTC, ewuerger commented on capellambse/model/layers/ctx.py
> +XT_CAP_EXP = "org.polarsys.capella.core.data.ctx:CapabilityExploitation"
You are right. I can swap the string with the classtype for xtypes in [Mission.exploits](https://github.com/DSD-DBS/py-capellambse/pull/102/files/9dff0998a5d6e4d193c19e4f83899a777d636675#diff-9461c9e412f391a413ece50fb2a1d724aeecba17a069cb5c44b79cdbf898358bR171-R176). Very good catch!

2022-06-23 07:23 UTC, ewuerger commented on capellambse/svg/drawing.py
> +                int(builder.label["x"])
I don't know. Even some lines after that `build.label["width']` is used without casting. Therefore changed as requested.

2022-06-23 07:33 UTC, ewuerger commented on capellambse/svg/generate.py
> +            self.drawing.filename = filename
That's why I like you to review my code. Very nice thank you.

2022-06-23 07:33 UTC, ewuerger commented on capellambse/model/layers/ctx.py
> +    ),
+1

2022-06-24 13:44 UTC, Wuestengecko approved these changes
Looks good now. LGTM.

2022-06-24 13:56 UTC, merged