Extract deprecated-alias logic to an Accessor
DSD-DBS/py-capellambse pull request #171
Opened 2022-10-26 14:50 UTC by Wuestengecko

There's not much logic here anyways, but this makes class bodies more streamlined and avoids repetitions.

2022-10-27 10:03 UTC, ewuerger requested changes
It always amazes me how the simple, short and therefore future-proof solutions you come up with have so much leverage: `DeprecatedAccessor`. I know that this one will be a great weapon in the battles (releases) of the future.

Paying attention to the documentation, I also noticed that we have long hyperlinks for the type annotations that come from **autodoc** [in PR#7018](https://github.com/sphinx-doc/sphinx/pull/7018) (**not** napoleon (!) ). Since we have a very structured code base with many submodules I want to shorten these.

The only thing that keeps you from merging this is resolving my suggestions.

2022-10-27 11:54 UTC, Wuestengecko commented on tests/test_model_layers.py
> +    @staticmethod
`@staticmethod` here only tells pylint that we don't need the `self` argument, so it won't complain about it missing. pytest (which runs this) doesn't care either way.

2022-10-27 12:27 UTC, Wuestengecko commented on tests/test_model_layers.py
> +        assert len(function.available_in_states) == 2
> I find it hilarious that I don't need to explicitly create a shallow copy

I don't think we should rely on this, see #176.

2022-10-27 12:31 UTC, Wuestengecko commented on capellambse/model/common/accessors.py
It wasn't used here before anyways (in fact there was a warning when it was set). This change makes it at least somewhat useful, by repurposing it for static type hints.

2022-10-27 12:35 UTC, Wuestengecko commented on tests/test_model_layers.py
> +        assert len(states) == 1
I didn't actually change these functions in any way, I only saw an opportunity to group them together. But good point, while we're here anyway :)

2022-10-28 08:27 UTC, Wuestengecko commented on capellambse/model/common/accessors.py
> +        objs = [i for i in elmlist if i != obj]
No, those would trigger a `delete` again and result in an infinite loop (or an exception, not sure).

2022-11-01 09:40 UTC, ewuerger approved these changes
LGTM

2022-11-01 09:51 UTC, merged