Add namespaces when creating elements
DSD-DBS/py-capellambse pull request #243
Opened 2023-02-09 14:35 UTC by Wuestengecko

In order for the types of model elements to be correctly identifiable, the namespace has to be defined on the fragment's respective root element. This commit adds new methods for this purpose, and ensures that `GenericElement.__init__` calls them with the correct values.

2023-02-10 11:11 UTC, ewuerger requested changes
I tested your implementation on a completely new Capella model and found out that the comment wasn't there anymore. `model.save()` would always give me the `"Cannot find Capella version: No version comment found"` warning, so I figured that there is something wrong.

Still the warning is there once when saving the model b/c in the `MelodyLoader.get_model_info` the `comment()` xpath isn't finding the version comment anymore... even though it is in the tree. I looked in it while debugging. I'd suggest that you add another test case that looks for all content before (comment) underneath (children) and after (probably nothing?) the project root element. Also it should be explained that capellambse isn't automating the tedious enabling of requirements via the viewpoints manager in Capella.

2023-02-10 14:11 UTC, Wuestengecko commented on capellambse/loader/core.py
> +            self.root.addprevious(i)
Nice catch. Yes, that was supposed to go to the `new_root`.

2023-02-10 14:25 UTC, Wuestengecko commented
The automatic viewpoint activation is not going to be part of this PR, as that can quickly grow too far out of scope (it involves the AFM file, which we currently don't use for anything yet). I've opened issue #245 to keep track of that.

2023-02-13 12:01 UTC, Wuestengecko commented
@ewuerger

> Still the warning is there once when saving the model b/c in the `MelodyLoader.get_model_info` the `comment()` xpath isn't finding the version comment anymore.

I can't repro after fixing the `new_root.addprevious()`. Can you retest with the newest version I just pushed? There's a new test for that, so you can just re-run the suite.

2023-02-14 13:03 UTC, ewuerger approved these changes
LGTM.

2023-02-14 15:01 UTC, ewuerger approved these changes
LGTM.

2023-02-14 15:03 UTC, merged